### ISSUE TITLE
Get tweets on data-range

### ISSUE THREAD

**Issue by ghost** [gadenbuie/gathertweet#5]
Hi,

Below code seems to fetch tweets for current day. 

`/usr/local/bin/gathertweet search --polite 'trump'`

Is there any way to add date range like last one week?

Any pointer will be highly appreciated.

Many thanks,

**Comment by gadenbuie** [comment]
The search term (here `'trump'`) can use any of the [advanced Twitter search terms](https://help.twitter.com/en/using-twitter/twitter-advanced-search). Try building your search using the twitter search page and then copy the final search terms to use with gathertweet. Note that you also need to increase the number of tweets to gather to get more results. You are currently only getting today because there are so many tweets matching “trump”.
